app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,RadioField,IntegerField,PasswordField,BooleanField,Label
from wtforms.validators import DataRequired,Email, EqualTo


class Form_Ssh(FlaskForm):
    id= StringField('Id',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Connect')

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template,redirect,flash,url_for
from flask_login import login_required
import simplejson as json
from ..models import VmMachine
from . import home
from bson import json_util
from forms import Form_Ssh
from flask_login import current_user
from fabric.api import local, run, cd, env, prefix
import winrm
@home.route('/')
def homepage():
    if current_user:
        return redirect('/dashboard')
    else:
     return redirect('/login')
@home.route('/dashboard',methods=['GET', 'POST'])
@login_required
def dashboard():
    machines = VmMachine.query.all()
    form = Form_Ssh()
    cnx=False
    if form.validate_on_submit():
        machine = VmMachine.query.get_or_404(form.id.data)
        cnx = test_connection(machine)
        if(form.password.data==machine.password_hs and cnx):

            return redirect(url_for('ssh.conection',id=machine.id))
        else:
            flash("Invalid Password or host not connect")
            print ("Invalid Password or host not connect")


    else:
      return render_template('home/dashboard.html',
                           machines=machines, title="machines",form=form)
@home.route('/machines/find/<int:id>', methods=['GET', 'POST'])
@login_required
def list_onemachine(id):
    machine =  VmMachine.query.get_or_404(id)
    return  json.dumps(machine,default=json_util.default)

def test_connection(machine):
    if (machine.os == 'windows'):
        try:
            s = winrm.Session(machine.ipAddress, auth=(machine.userName, machine.password_hs))
            r = s.run_cmd('ipconfig')
            print (r.std_out)
            return True
        except Exception, e:
            print (e)
            r.std_err
            return False
    elif (machine.os == 'linux'):
        try:
            env.host_string = machine.userName + '@' + machine.ipAddress
            env.password = machine.password_hs
            run('ifconfig')
            return True
        except Exception, e:
            print('' + str(e))
            return False

app/templates/Home.html
{% block body %}
 <div id="left-menu">
              <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li><div class="left-bg"></div></li>
                    <li class="time">
                      <h1 class="animated fadeInLeft"></h1>
                      <p class="animated fadeInRight"></p>
                    </li>
                    <li class="active ripple">
                      <a class="tree-toggle nav-header"><span class="fa-home fa"></span> Dashboard
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                          <li><a href="dashboard-v1.html">Dashboard v.1</a></li>
                          <li><a href="dashboard-v2.html">Dashboard v.2</a></li>
                      </ul>
                    </li>
                    <li><a href="credits.html">Credits</a></li>
                  </ul>
                </div>
            </div>
            <div id="content">
                        <div class="col-md-4" style="margin-top: 10px">
                            <div class="col-md-8 padding-0">
                              <div class="panel box-v2">
                                  <div class="panel-heading padding-0">
                                    <img src="" class="box-v2-cover img-responsive"/>
                                    <div class="box-v2-detail">
                                      <img src="" class="img-responsive"/>
                                      <h4>Akihiko Avaron</h4>
                                    </div>
                                  </div>
                                  <div class="panel-body">
                                    <div class="col-md-12 padding-0 text-center">
                                      <div class="col-md-4 col-sm-4 col-xs-6 padding-0">
                                          <h3>2.000</h3>
                                          <p>Post</p>
                                      </div>
                                      <div class="col-md-4 col-sm-4 col-xs-6 padding-0">
                                          <h3>2.232</h3>
                                          <p>share</p>
                                      </div>
                                      <div class="col-md-4 col-sm-4 col-xs-12 padding-0">
                                          <h3>4.320</h3>
                                          <p>photos</p>
                                      </div>
                                    </div>
                                  </div>
                              </div>
                            </div>
                        </div>
            </div>
{% endblock %}

app/templates/Login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="description" content="RemoteControle Template">
	<meta name="keyword" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} | Dashbord</title>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/font-awesome.min.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/simple-line-icons.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/simple-line-icons.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/animate.min.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/fullcalendar.min.css') }}"/>
	  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
      <link rel="shortcut icon" href="{{ url_for('static', filename='img/logomi.png') }}">
  </head>
 <body id="mimin" class="dashboard form-signin-wrapper">

      <div class="container">

        <form class="form-signin" method="post" action="/login">
          <div class="panel periodic-login">
              <div class="panel-body text-center">
                  <h1>Remote Controle</h1>
                  <p class="atomic-mass"></p>
                  <p class="element-name">Vermeg</p>

                  <i class="icons icon-arrow-down"></i>
                  <div class="form-group form-animate-text" style="margin-top:40px !important;">
                    {{form.email(class='form-text',type='text')}}
                    <span class="bar"></span>
                    <label>Email</label>
                  </div>
                  <div class="form-group form-animate-text" style="margin-top:40px !important;">
                    {{form.email(class='form-text',type='password')}}
                    <span class="bar"></span>
                    <label>Password</label>
                  </div>
                  <input type="submit" class="btn col-md-12" value="SignIn"/>
              </div>
          </div>
        </form>

      </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.ui.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/jquery.nicescroll.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/jquery.vmap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/maps/jquery.vmap.world.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/jquery.vmap.sampledata.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/chart.min.js') }}"></script>

     <script src="{{ url_for('static', filename='js/main.js') }}"></script>

  </body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en" ng-app="myApp">
<head>
	<meta charset="utf-8">
	<meta name="description" content="RemoteControle Template">
	<meta name="keyword" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }} | Dashbord</title>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/font-awesome.min.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/simple-line-icons.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/simple-line-icons.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/animate.min.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/fullcalendar.min.css') }}"/>
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/plugins/spinkit.css') }}"/>
	  <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
      <link rel="shortcut icon" href="{{ url_for('static', filename='img/logomi.png') }}">
    <script src="{{ url_for('static', filename='js/angular.js') }}"></script>


    {% block angularjs %}{% endblock %}

  </head>
<body id="mimin" class="dashboard" ng-controller="DashCtrl">
        <nav class="navbar navbar-default header navbar-fixed-top">
          <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
                <a href="index.html" class="navbar-brand">
                 <b>Remote Controle</b>
                </a>
                {% if current_user.is_authenticated %}
              <ul class="nav navbar-nav navbar-right user-nav">
                <li class="user-name"><span>{{ current_user.username }}</span></li>
                  <li class="dropdown avatar-dropdown">
                   <img src="{{ url_for('static', filename='img/avatar.png') }}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                </li>
                <li ><a href="{{ url_for('auth.logout') }}"><span class="fa fa-power-off"></span></a></li>
              </ul>
                {% endif %}
            </div>
          </div>
        </nav>
      <div class="container-fluid mimin-wrapper">
      <div id="left-menu">
              <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li><div class="left-bg"></div></li>
                    <li class="time">
                      <h1 class="animated fadeInLeft"></h1>
                      <p class="animated fadeInRight"></p>
                    </li>
                    <li><a href="{{ url_for('home.dashboard') }}" class="tree-toggle nav-header"><span class="fa-home fa"></span>Dashboard</a></li>
                      {% if current_user.is_admin %}
                    <li class="active ripple">
                      <a class="tree-toggle nav-header"><span class="fa-search-plus fa"></span>Administration
                        <span class="fa-angle-right fa right-arrow text-right"></span>
                      </a>
                      <ul class="nav nav-list tree">
                          <li><a href="{{ url_for('admin.list_machines') }}">Gestion Machine Virtuel</a></li>
                          <li><a href="{{ url_for('admin.list_users') }}">Gestion Utilisateur</a></li>
                          <li><a href="{{ url_for('admin.list_configs') }}">Gestion Configuration</a></li>
                          <li><a href="{{ url_for('admin.list_programmes') }}">Gestion Progarmme</a></li>
                      </ul>
                    </li>
                    {% endif %}
                  </ul>
                </div>
      </div>
  {% block body %}{% endblock %}
      </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.ui.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/moment.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/jquery.nicescroll.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/jquery.vmap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/maps/jquery.vmap.world.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/jquery.vmap.sampledata.js') }}"></script>
     <script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% block scriptjs %}{% endblock %}
  </body>
</html>